title: Enguerran COBERT 
theme: jekyll-theme-tactile
description: "Gameplay Programmer | Unreal & Unity"

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /aboutme
  - title: "Projects"
    url: /projects
