title: Enguerran COBERT 
theme: minimal-mistakes-jekyll
description: "Gameplay Programmer | Unreal & Unity"

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /aboutme
  - title: "Spawn System Using Spatial Hashing"
    url: /SSSH
  - title: "A* Pathfinding"
    url: /AStartPF
